# fly.toml app configuration file generated for trashcar-ppkk on 2023-05-06T19:47:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# fly.io所設置的app名稱
app = "hsr_sign"
# 指定app的主要地區
primary_region = "hkg"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

# 設定環境變數，讓主程式讀取COOKIES, API_KEY, CHAT_ID
[env]
# 有多個帳號需要簽到的話請用逗號分隔
# COOKIES='cookie1,cookie2,cookie3'
COOKIES='YOUR_COOKIES'
# 有多個telegram帳號需要回傳簽到結果的話請用逗號分隔
# CHAT_ID='id1,id2,id3'
CHAT_ID='YOUR_TELEGRAM_CHAT_ID'
API_KEY='YOUR_TELEGRAM_BOT_API'